### ISSUE TITLE
+12504798004 is a Canadian number but resolves to U.S.A.

### ISSUE THREAD

**Issue by ghost** [relops/prefixes#1]

**Comment by 0x6e6562** [comment]
OK, I've got 250 mapped as an area code of Alaska and also of BC. So there is a conflict there. I will look into which way round it should be and correct the data accordingly.

BTW, in what area should `+12504798004` be?

**Comment by ghost** [comment]
250 is British Columbia. The other 2 area codes in BC are 778 and 604. 250 covers Vancouver Island and parts of BC outside of Vancouver (the city).

**Comment by 0x6e6562** [comment]
OK, cool - the data that is currently being used for BC is:

```
British Columbia,236,250,604,672,778
```

But due to that Alaska bug, the 250 is being shadowed. I'm right in the middle of a release of some other system right now, but I'll fix this as soon as I can.
